- name: Set up i3wm and polybar with configs
  hosts: localhost
  connection: local
  roles:
    - i3wm
    - dmenu
    - polybar
    - bash
    - clipmenu
    - alacritty
    - neovim
    - create-pwa
    - additional-deps
