[colors.bright]
blue = "0x8ABEB7"
green = "0xb5bd68"
red = "0xF0C674"

[colors.primary]
#background = "0x282A2E"
background = "0x000000"
foreground = "0xC5C8C6"

[font]
size = 11.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[window]
decorations = "none"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 8 # Matched to i3 gaps inner
y = 8 # Matched to i3 gaps inner

