[colors.bright]
blue = "0x81a2be"
green = "0xb5bd68"
red = "0xcc6666"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[font]
size = 11.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[window]
decorations = "none"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
y = 5
