- name: Install required packages for clipmenu and clipnotify
  dnf:
    name:
      - gcc
      - make
      - libXfixes-devel
      - libX11-devel
      - xsel
    state: present
  become: true

- name: Clone clipnotify from GitHub
  git:
    repo: 'https://github.com/cdown/clipnotify.git'
    dest: '~/clipnotify'
    clone: yes
    update: yes
  become: true

- name: Compile and install clipnotify
  make:
    chdir: '~/clipnotify'
    target: install
  become: true

- name: Clone clipmenu from GitHub
  git:
    repo: 'https://github.com/cdown/clipmenu.git'
    dest: '~/clipmenu'
    clone: yes
    update: yes
  become: true

- name: Compile and install clipmenu
  make:
    chdir: '~/clipmenu'
    target: install
  become: true

- name: Ensure systemd user directory exists
  file:
    path: "~/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Copy clipmenud systemd service file
  ansible.builtin.copy:
    src: "roles/clipmenu/files/clipmenud.service"
    dest: "~/.config/systemd/user/clipmenud.service"
    mode: '0644'

- name: Enable and start clipmenud service for current user
  systemd:
    name: clipmenud
    state: started
    enabled: yes
    scope: user
    daemon_reload: yes

