- name: Install polybar
  dnf:
    name:
      - polybar
    state: present
  become: yes

- name: Copy polybar config files
  ansible.builtin.copy:
    src: "roles/polybar/files/"
    dest: "~/.config/"
    directory_mode: '0755'
    mode: '0644'
    remote_src: no
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  delegate_to: localhost
  
