---
- name: Install polybar
  ansible.builtin.dnf:
    name:
      - polybar
    state: present
  become: true

- name: Install power-profiles-daemon for power profile switching
  ansible.builtin.dnf:
    name:
      - power-profiles-daemon
    state: present
  become: true

- name: Copy polybar config files
  ansible.builtin.copy:
    src: files/ # Ansible automatically looks in role's files dir
    dest: "{{ ansible_env.HOME }}/.config/polybar/"
    directory_mode: '0755'
    mode: '0644' # Scripts made executable in next task
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Collect scripts from polybar config directory
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/.config/polybar/"
    patterns: "*.sh"
    recurse: yes # Set to no if scripts are only in the top directory
  register: polybar_scripts_to_make_executable

- name: Make polybar scripts executable
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: '0755' # u+x, g+x, o+x
  with_items: "{{ polybar_scripts_to_make_executable.files }}"
  when: polybar_scripts_to_make_executable.matched > 0
