- name: Install i3wm
  dnf:
    name:
      - i3
    state: present
  become: yes

- name: Copy i3wm config files
  ansible.builtin.copy:
    src: "roles/i3wm/files/"
    dest: "~/.config/"
    directory_mode: '0755'
    mode: '0644'
    remote_src: no
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
 
