- name: Install i3wm
  dnf:
    name:
      - i3
      - light
      - xset
      - pass
      - passmenu
      - surfraw
    state: present
  become: true

- name: Copy i3wm config files
  ansible.builtin.copy:
    src: "roles/i3wm/files/"
    dest: "~/.config/i3/"
    directory_mode: '0755'
    mode: '0644'
    remote_src: no
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Collect scripts
  ansible.builtin.find:
    paths: "~/.config/i3/"
    patterns: "*.sh"
    recurse: yes
  register: scripts

- name: Make scripts executable
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: 'u+x'
  with_items: "{{ scripts.files }}"
