---
- name: Install cryptsetup and related packages
  package:
    name:
      - cryptsetup
      - cryptsetup-luks
      - btrfs-progs  # BTRFS utilities
      - compsize     # Check compression ratios
    state: present
  become: true

- name: Create mount point directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /backup
    - /secrets
    - /toast
  become: true

- name: Add encrypted partitions to /etc/crypttab
  lineinfile:
    path: /etc/crypttab
    line: "{{ item.name }} {{ item.device }} none luks,noauto"
    state: present
    create: true
  loop:
    - { name: "backup", device: "UUID={{ backup_partition_uuid }}" }
    - { name: "secrets", device: "UUID={{ secrets_partition_uuid }}" }
    - { name: "toast", device: "UUID={{ toast_partition_uuid }}" }
  become: true
  when: 
    - backup_partition_uuid is defined
    - secrets_partition_uuid is defined
    - toast_partition_uuid is defined

- name: Add mount entries to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "/dev/mapper/{{ item.name }} {{ item.mount }} btrfs defaults,noauto,compress=zstd 0 0"
    state: present
  loop:
    - { name: "backup", mount: "/backup" }
    - { name: "secrets", mount: "/secrets" }
    - { name: "toast", mount: "/toast" }
  become: true

- name: Copy encrypted drives mount script
  copy:
    src: add_encrypted_drives_to_dmenu.sh
    dest: "{{ ansible_env.HOME }}/.config/i3/scripts/add_encrypted_drives_to_dmenu.sh"
    mode: '0755'

- name: Create systemd user directory
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Template storage mount helper script
  template:
    src: storage-mount-helper.sh.j2
    dest: "{{ ansible_env.HOME }}/.local/bin/storage-mount-helper.sh"
    mode: '0755'

- name: Ensure .local/bin directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'
