- name: Install Neovim
  dnf:
    name: neovim
    state: present
  become: yes

- name: Copy Neovim config files
  ansible.builtin.copy:
    src: "roles/neovim/files/"
    dest: "~/.config/"
    directory_mode: '0755'
    mode: '0644'
    remote_src: no
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  delegate_to: localhost

