---
- name: Install additional dependencies
  ansible.builtin.dnf:
    name:
      - dunst  # For notifications
      - libnotify  # For notify-send
      - xsetroot  # For setting X background
    state: present
  become: true
  # ignore_errors: true # It's better to handle missing packages explicitly or find alternatives